name: "ESP-IDF build artifacts - new"

on:
  push:
      branches:
        - master
      paths-ignore:
        - '.github/workflows/build-artifact.yml'
        - '.github/workflows/build-artifact-on-push.yml'

jobs:
  build-and-upload-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v4.4
          target: esp32
          command: |
            idf.py build
            cd build
            esptool.py --chip esp32 merge_bin -o merged-flash.bin @flash_args
            cd ..

      - name: Create artifact name
        run: echo "artifact_name=esp32-bin-merged" >> $GITHUB_ENV

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.artifact_name }}"
          path: build/merged-flash.bin
